import = ["~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"]

[window]
opacity = 1.0
padding = { x = 0, y = 0 }
dynamic_padding = true

[shell]
program = "/bin/zsh"

[font]
size = 7

normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
